protected/modules/schoolconfig/controllers/SubjectsController.php
<?php

/*
 * © 2015 LOGIPAM services / www.logipam.com siges@logipam.com et contributeurs (voir www.logipam.com)
 * 
 * This file is part of SIGES.

    SIGES is a free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    SIGES is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SIGES.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */



class SubjectsController extends Controller
{
	public $layout='//layouts/column2';
	private $_model;
	
	public $back_url='';
	public $is_subject_parent;
	
	

	public function filters()
	{
		return array(
			'accessControl', 
		);
	}

	public function accessRules()
	{
		    
            $explode_url= explode("/",substr($_SERVER['REQUEST_URI'], 1));
            $controller=$explode_url[3];
            
            $actions=$this->getRulesArray($this->module->name,$controller);
              
            if($this->getModuleName($this->module->name))
                {
		            if($actions!=null)
             			 {     return array(
				              	  	array('allow',  
					                	
					                	'actions'=> $actions,
		                                  'users'=>array(Yii::app()->user->name),
				                    	),
				              		  array('deny',  
					                 	'users'=>array('*'),
				                    ),
			                );
             			 }
             			 else
             			  return array(array('deny', 'users'=>array('*')),);
                }
                else
                {
                    return array(array('deny', 'users'=>array('*')),);
                }


	}

	public function actionView()
	{
		$this->render('view',array(
			'model'=>$this->loadModel(),
		));
	}

	public function actionCreate()
	{
		$model=new Subjects;
               
               
                            
                $this->performAjaxValidation($model);

		if(isset($_POST['Subjects']))
		{
			
			     if(isset($_POST['Subjects']['is_subject_parent']))
			         { $this->is_subject_parent=$_POST['Subjects']['is_subject_parent']; 
			           
			           
			         }
			      
			
			$model->attributes=$_POST['Subjects'];
			
			if(isset($_POST['create']))
			 {
				if($this->is_subject_parent == 1)
				  {
				  	  $model->setAttribute('subject_parent',null);
				  	}
				  	
				$model->setAttribute('date_created',date('Y-m-d'));
				$model->setAttribute('date_updated',date('Y-m-d'));
			
	            
				if($model->save())
	                                //Recdirect to manage 
	                                $this->redirect (array('index'));
					
		       }
		       
		       if(isset($_POST['cancel']))
				 {
                    $this->redirect(Yii::app()->request->urlReferrer);
                         }
		}

		$this->render('create',array(
			'model'=>$model,
		));
	}

	public function actionUpdate()
	{
		
               
        $model=$this->loadModel();
                
        $this->is_subject_parent = $model->is_subject_parent;
                
		$this->performAjaxValidation($model);
           
            	            

		if(isset($_POST['Subjects']))
		{
			
			     if(isset($_POST['Subjects']['is_subject_parent']))
			         { $this->is_subject_parent=$_POST['Subjects']['is_subject_parent']; 
			           
			           
			         }
			      
			
			$model->attributes=$_POST['Subjects'];
			
			if(isset($_POST['update']))
			 {
				if($this->is_subject_parent == 1)
				  {
				  	  $model->setAttribute('subject_parent',null);
				  	}
				
				$model->setAttribute('date_updated',date('Y-m-d'));
	                        
				if($model->save())
	                            //Redirect to amdmin 
	                            $this->redirect(array('index'));
					
			  }
			  
			 
			 if(isset($_POST['cancel']))
				 {
                    $this->redirect(Yii::app()->request->urlReferrer);
                         }
			  
			       
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	public function actionDelete()
	{
		
		
		try {
   			 
   			 
   			$model=$this->loadModel();
	        
	        $subject_id= $model->id;
	        
	         $this->loadModel()->delete();

	           			 
   			 // if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
			  if(!isset($_GET['ajax']))
				$this->redirect(array('index'));
			
			} catch (CDbException $e) {
			    if($e->errorInfo[1] == 1451) {
			        
			        header($_SERVER["SERVER_PROTOCOL"]." 500 Relation Restriction");
			        echo Yii::t('app',"\n\n There are dependant elements, you have to delete them first.\n\n");
			    } else {
			        throw $e;
			    }
			}



	}



        // Update the actionAdmin() en actionIndex()
	public function actionIndex()
	{
		
                if (isset($_GET['pageSize'])) {
                    Yii::app()->user->setState('pageSize',(int)$_GET['pageSize']);
                    unset($_GET['pageSize']);
                    }
                $model=new Subjects('search');
                $model->unsetAttributes();
                
		if(isset($_GET['Subjects']))
			$model->attributes=$_GET['Subjects'];
		
		// Here to export to CSV 
		if($this->isExportRequest()){
		$this->exportCSV(array(Yii::t('app','List of subjects: ')), null,false);
		
		$this->exportCSV($model->search(), array(
		'subject_name',
		'subjectParent.subject_name',
		'isParent',)); 
		}

		$this->render('index',array(
			'model'=>$model,
		));
	}

	public function loadModel()
	{
		if($this->_model===null)
		{
			if(isset($_GET['id']))
				$this->_model=Subjects::model()->findbyPk($_GET['id']);
			if($this->_model===null)
				throw new CHttpException(404, Yii::t('app', 'The requested page does not exist.'));
		}
		return $this->_model;
	}

	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='subjects-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
	
	// Export to CSV 
	public function behaviors() {
	   return array(
	       'exportableGrid' => array(
	           'class' => 'application.components.ExportableGridBehavior',
	           'filename' => Yii::t('app','subjects.csv'),
	           'csvDelimiter' => ',',
	           ));
	}
        
        
        public  function actionMassAddingSubjects(){
            $model = new Subjects;
            $number_line = infoGeneralConfig('nb_grid_line');
            $subject_label = array(); 
			$short_subject_label = array(); 
            $is_subject_parent = array(); 
            $parent_subject = array();
            $error_report = False;
            $subject_name = array();
			$short_subject_name = array();
            $j = 0;
            if(isset($_POST['btnSave'])){
                for($i=0; $i<$number_line;$i++){
                    if((isset($_POST['subject_label'.$i]) && $_POST['subject_label'.$i]!="")&&((isset($_POST['short_subject_label'.$i]) && $_POST['short_subject_label'.$i]!=""))){
                        //Verifie si is_subject_parent est coche
                        if(isset($_POST['is_subject_parent'])){
                            $is_subject_parent[$i] = 1;
                        }else{
                            $is_subject_parent[$i] = 0;
                        }
                        $subject_label[$i] = $_POST['subject_label'.$i];
						$short_subject_label[$i] = $_POST['short_subject_label'.$i];
                        if(isset($_POST['parent_subject'.$i]) && $_POST['parent_subject'.$i] !=""){
                             $parent_subject[$i] = $_POST['parent_subject'.$i];
                        }else{
                             $parent_subject[$i] = null;
                        }
                       
                        $model->setAttribute('subject_name', $subject_label[$i]);
						$model->setAttribute('short_subject_name', $short_subject_label[$i]);
                        $model->setAttribute('is_subject_parent', $is_subject_parent[$i]);
                        $model->setAttribute('subject_parent', $parent_subject[$i]);
                        $model->setAttribute('date_created', date('Y-m-d H:m:s'));
                        $model->setAttribute('create_by', currentUser());
                        if($model->save()){
                            
                        }else{
                            $error_report = True;
                            $subject_name[$j] = $subject_label[$i];
                            $j++;
                        }
                    }
                    $model->unsetAttributes(); 
                    $model = new Subjects; 
                }
                
                if($error_report){
                    $liste_subject = "";
                  for($i=0; $i<count($subject_name); $i++){
                      $liste_subject .= $subject_name[$i].'<br/>';
                  }
                  $message=Yii::t('app',"At least {name} error(s) occured when you saved subjects !<br/> The following subjects were about to be duplicated:<br/><b> {subject}</b>",array('{name}'=>$j,'{subject}'=>$liste_subject));
                 Yii::app()->user->setFlash(Yii::t('app','Error'), $message);
                }
                $this->redirect(array('index'));
            }
            
            
            $this->render('gridcreate',array('model'=>$model));
        }
	
	
	
}

protected/modules/schoolconfig/views/subjects/_form.php
<?php

/*
 * © 2015 LOGIPAM services / www.logipam.com siges@logipam.com et contributeurs (voir www.logipam.com)
 * 
 * This file is part of SIGES.

    SIGES is a free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    SIGES is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SIGES.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

$acad_sess=acad_sess();
$acad=Yii::app()->session['currentId_academic_year'];


?>
<?php $this->widget('ext.yiiselect2.YiiSelect2',array('target'=>'select',)); ?>

<?php
	echo '<p class="note">'.Yii::t('app','Fields with <span class="required">*</span> are required.').'</p>';

	  echo $form->errorSummary($model); ?>

		
   
<div  id="resp_form_siges">

<form  id="resp_form">



	  <div class="col-4">
			    <label id="resp_form">

<?php echo $form->labelEx($model,'subject_name'); ?>
                              <?php echo $form->textField($model,'subject_name',array('size'=>60,'maxlength'=>45,'placeholder'=>Yii::t('app','Subject Name'))); ?>
                              <?php echo $form->error($model,'subject_name'); ?>
              </label>
</div>
	
	
<div class="col-4">
			    <label id="resp_form">

<?php echo $form->labelEx($model,'short_subject_name'); ?>
                              <?php echo $form->textField($model,'short_subject_name',array('size'=>60,'maxlength'=>5,'placeholder'=>Yii::t('app','Short Subject Name'))); ?>
                              <?php echo $form->error($model,'short_subject_name'); ?>
              </label>
</div>	
	
<div class="col-4">
	<label id="resp_form">

<?php echo $form->labelEx($model,'is_subject_parent'); ?>
                              <?php 
                              if($this->is_subject_parent==1)
								{
									echo $form->checkBox($model,'is_subject_parent',array('onchange'=> 'submit()','checked'=>'checked') ); 
								
								}
						      elseif($this->is_subject_parent==0)
						        {
						        	echo $form->checkBox($model,'is_subject_parent',array('onchange'=> 'submit()') );
						          }
									
									
									?>
                              <?php echo $form->error($model,'is_subject_parent'); ?>
   </label>
</div>
	
	
<?php
    if($this->is_subject_parent==0)
		{

?>
<div class="col-4">
	<label id="resp_form">

<?php echo Yii::t('app','Parent Subjects'); ?>
                         <div> <?php 
			
								$criteria = new CDbCriteria(array('order'=>'subject_name','condition'=>'is_subject_parent=1'));
								
								echo $form->dropDownList($model, 'subject_parent',
								CHtml::listData(Subjects::model()->findAll($criteria),'id','subject_name'),
								array('prompt'=>Yii::t('app','-- Please select subject --'))
								);
								 ?></div>
					      </label>
</div>
	
<?php
    
		}

?>	
		

                           <div class="col-submit">
                                
                                <?php if(!isset($_GET['id'])){
                                          if(!isAchiveMode($acad_sess))
                                              echo CHtml::submitButton(Yii::t('app', 'Create '),array('name'=>'create','class'=>'btn btn-warning')); //'Create ' avec espace a la fin POUR AVOIR UNE TRADUCTION "ENREGISTRER"
                                         
                                         echo CHtml::submitButton(Yii::t('app', 'Cancel '),array('name'=>'cancel','class'=>'btn btn-secondary')); //'Cancel ' avec espace a la fin POUR AVOIR UNE TRADUCTION "Annuler"/ sans espace=>'Retour'
                                        }
                                         else
                                           {   if(!isAchiveMode($acad_sess))
                                                  echo CHtml::submitButton(Yii::t('app', 'Save'),array('name'=>'update','class'=>'btn btn-warning'));
                                            
                                              echo CHtml::submitButton(Yii::t('app', 'Cancel '),array('name'=>'cancel','class'=>'btn btn-secondary'));
                                              
                                             } 
                                           //back button   
                                              $url=Yii::app()->request->urlReferrer;
                                              $explode_url= explode("php",substr($url,0));
				             
                                              echo ' <a href="'.$explode_url[0].'php'.$this->back_url.'" class="btn btn-secondary">'.Yii::t('app', 'Back').'</a>';
                                          

                                            
                                ?>
                                
                           
                </div>
                
              </form>

</div><!-- END OF TEST -->
   
   
   
   
   
   
   
   
   

protected/modules/schoolconfig/views/subjects/_gridcreate.php
<?php

/*
 * © 2016 LOGIPAM services / www.logipam.com siges@logipam.com et contributeurs (voir www.logipam.com)
 * 
 * This file is part of SIGES.

    SIGES is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    SIGES is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SIGES.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

$acad_sess=acad_sess();
$acad=Yii::app()->session['currentId_academic_year'];
?>

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'fees-grid-add',
	'enableAjaxValidation'=>false,
));

$acad=Yii::app()->session['currentId_academic_year'];

    function evenOdd($num)
            {
                ($num % 2==0) ? $class = 'odd' : $class = 'even';
                return $class;
            }

if(infoGeneralConfig('nb_grid_line')!=null){
    $number_line = infoGeneralConfig('nb_grid_line');
}else{
    $number_line = 6; 
}            
            
?>




<div class="grid-view">
    
    
   
    
    <table class="items">
        <tr>
        <th><?php echo Yii::t('app','Subject Name'); ?></th>
		 <th><?php echo Yii::t('app','Short Subject Name'); ?></th>
        <th><?php echo Yii::t('app','Is Subject Parent'); ?></th>
      
        <th><?php echo Yii::t('app','Parent Subjects'); ?></th>
       
        </tr>
        
        <?php for($i=0; $i<$number_line; $i++){ ?>
        <tr class="<?php echo evenOdd($i); ?>">
            <td>
                <input type="text"  size="60" name="subject_label<?php echo $i; ?>" placeholder="<?php echo Yii::t('app','Subject Name'); ?>" />
            </td>
			<td>
                <input type="text"  size="60" name="short_subject_label<?php echo $i; ?>" placeholder="<?php echo Yii::t('app','Short Subject Name'); ?>" />
            </td>
            <td>
                <div class="checkbox_view"><input  id="active" type="checkbox" name="is_subject_parent<?php echo $i ?>"/></div>
            </td>
            
            <td>
                <?php 
			
                        $criteria = new CDbCriteria(array('order'=>'subject_name','condition'=>'is_subject_parent=1'));

                        echo $form->dropDownList($model, 'subject_parent',
                        CHtml::listData(Subjects::model()->findAll($criteria),'id','subject_name'),
                        array('prompt'=>Yii::t('app','-- Please select subject --'),'name'=>'parent_subject'.$i)
                        );
                 ?>
            </td>
            
           
            
        </tr>      
        <?php } ?>
        
        
    </table>
    
    <div class="col-submit"> 
 <?php 
               if(!isAchiveMode($acad_sess))
                 {       
        ?>
              
        <button name="btnSave" class="btn btn-warning" type="submit"><?php echo Yii::t('app','Save');  ?></button>
    <?php
                 }
      
      ?>        
        <button name="btnCancel" class="btn btn-secondary" type="submit"><?php echo Yii::t('app','Cancel ');  ?></button>
    </div>
    
   
</div>


<?php $this->endWidget(); ?>
            

protected/modules/schoolconfig/views/subjects/_search.php
<?php

/*
 * © 2015 LOGIPAM services / www.logipam.com siges@logipam.com et contributeurs (voir www.logipam.com)
 * 
 * This file is part of SIGES.

    SIGES is a free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    SIGES is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SIGES.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

?>
<div class="wide form">

<?php $form=$this->beginWidget('CActiveForm', array(
        'action'=>Yii::app()->createUrl($this->route),
        'method'=>'get',
)); ?>

        

        <div class="row">
                
                <?php echo $form->textField($model,'subject_name',array('size'=>20,'maxlength'=>20,'placeholder'=>Yii::t('app','Subject name'))); ?>
                <?php echo CHtml::submitButton(Yii::t('app', 'Search')); ?>
        </div>

<?php $this->endWidget(); ?>

</div><!-- search-form -->

protected/modules/schoolconfig/views/subjects/index.php
<?php

/*
 * © 2015 LOGIPAM services / www.logipam.com siges@logipam.com et contributeurs (voir www.logipam.com)
 * 
 * This file is part of SIGES.

    SIGES is a free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    SIGES is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SIGES.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

$acad_sess=acad_sess();
$acad=Yii::app()->session['currentId_academic_year'];

$template ='';

?>
<?php
$this->breadcrumbs=array(
	Yii::t('app','Subjects')=>array('index'),
	Yii::t('app', 'Manage'),
);

?>




<!-- Menu of CRUD  -->
<div id="dash">
          
          <div class="span3"><h2>
<?php echo Yii::t('app', 'Subject');?> 
</h2> </div> 
     
		   <div class="span3">
  
          <?php 
               if(!isAchiveMode($acad_sess))
                 {     $template ='{update}{delete}';    
        ?>

           	      
	      <div class="span4">				
                  <?php   $images = '<i class="fa fa-plus">&nbsp;'.Yii::t('app','Add').'</i>';
                               // build the link in Yii standard
                     echo CHtml::link($images,array('subjects/create')); 
                   ?>
                  </div>
                       
                        <?php if(infoGeneralConfig('grid_creation')!=null){ ?>
                       <div class="span4">
                          <?php  
                          $images = '<i class="fa fa-table"> &nbsp; '.Yii::t('app','Mass adding').'</i>'; 
                          echo CHtml::link($images,array('subjects/massAddingSubjects'));
                          ?>
                       </div>              
                       
                       <?php } ?> 
      <?php
                 }
      
      ?>       

                  
                <div class="span4">
                      <?php
				
                     $images = '<i class="fa fa-arrow-left"> &nbsp;'.Yii::t('app','Cancel').'</i>';

                               // build the link in Yii standard
                     echo CHtml::link($images,array('/academic/persons/viewListAdmission/isstud/1/pg/lr/mn/std')); 
                   ?>
                  </div>   


        </div>          
                           
</div>



<div style="clear:both"></div>


<?php


		Yii::app()->clientScript->registerScript('search', "
			$('.search-button').click(function(){
				$('.search-form').toggle();
				return false;
				});
			$('.search-form form').submit(function(){
				$.fn.yiiGridView.update('subjects-grid', {
data: $(this).serialize()
});
				return false;
				});
			");
		?>




<div  class="search-form">
<?php 
        
		  $this->renderPartial('_search',array(
	'model'=>$model,
)); ?>
</div>

<div class="clear"></div>


<?php 
        $pageSize=Yii::app()->user->getState('pageSize',Yii::app()->params['defaultPageSize']);
        $gridWidget = $this->widget('groupgridview.GroupGridView', array(
	'id'=>'subjects-grid',
	'dataProvider'=>$model->searchReport(),
	'mergeColumns'=>'subjectParent.subject_name',
	'columns'=>array(
		
                 array(
                    'name' => 'subjectParent.subject_name',
                    'htmlOptions'=>array('width'=>'250px'),
                ),
		 array(
                    'name' => 'subject_name',
                    'type' => 'raw',
                    'value'=>'CHtml::link($data->subject_name,Yii::app()->createUrl("/schoolconfig/subjects/view",array("id"=>$data->id)))',
                    'htmlOptions'=>array('width'=>'250px'),
                ),

         array(
                    'name' => 'short_subject_name',
                    'type' => 'raw',
                    'value'=>'CHtml::link($data->short_subject_name,Yii::app()->createUrl("/schoolconfig/subjects/view",array("id"=>$data->id)))',
                    'htmlOptions'=>array('width'=>'250px'),
                ),				
		
		array(
			'class'=>'CButtonColumn',
                        'template'=>$template,
                        'buttons'=>array('update'=>array('label'=>'<span class="fa fa-pencil-square-o"></span>',
                            'imageUrl'=>false,
                            'options'=>array('title'=>Yii::t('app','Update')),
                             
                            ),
                            'delete'=>array('label'=>'<span class="fa fa-trash-o"></span>',
                            'imageUrl'=>false,
                            'options'=>array('title'=>Yii::t('app','Delete')),
                                
                            ),
                            ),
                        'header'=>CHtml::dropDownList('pageSize',$pageSize,array(10=>10,20=>20,50=>50,100=>100),array(
                         'onchange'=>"$.fn.yiiGridView.update('subjects-grid',{ data:{pageSize: $(this).val() }})",
            )),
		),
	),
)); 

$content=$model->searchReport()->getData();
        if((isset($content))&&($content!=null))
              $this->renderExportGridButton($gridWidget, '<i class="fa fa-arrow-right"></i>'.Yii::t('app',' CSV'),array('class'=>'btn-info btn'));
?>

protected/modules/schoolconfig/views/subjects/update.php
<?php

/*
 * © 2015 LOGIPAM services / www.logipam.com siges@logipam.com et contributeurs (voir www.logipam.com)
 * 
 * This file is part of SIGES.

    SIGES is a free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    SIGES is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SIGES.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

?>




<!-- Menu of CRUD  -->
    
<?php
$acad_sess=acad_sess();


$this->breadcrumbs=array(
	Yii::t('app','Subjects')=>array('index'),
	$model->subject_name,
);
?>

<div id="dash">
          
          <div class="span3"><h2>
<?php echo  Yii::t('app','Update : {name}',array('{name}'=>$model->subject_name))?>
</h2> </div>
     
		   <div class="span3">
   <?php 
               if(!isAchiveMode($acad_sess))
                 {       
        ?>		   
             <div class="span4">				
                  <?php   $images = '<i class="fa fa-plus">&nbsp;'.Yii::t('app','Add').'</i>';
                               // build the link in Yii standard
                     echo CHtml::link($images,array('subjects/create')); 
                   ?>
               </div>
  <?php
                 }
  ?>                
              <div class="span4">
                  <?php
				
                     $images = '<i class="fa fa-arrow-left"> &nbsp;'.Yii::t('app','Cancel').'</i>';

                               // build the link in Yii standard
                     if(isset($_GET['from'])){
                        
                        if($_GET['from']=='view')
                        {
                            echo CHtml::link($images,array('/schoolconfig/subjects/view','id'=>$_GET['id']));
                            $this->back_url='/schoolconfig/subjects/view?id='.$_GET['id'];
                        }
                      }
                      else
                        {    echo CHtml::link($images,array('/schoolconfig/subjects/index')); 
                           $this->back_url='/schoolconfig/subjects/index';
                        }
                   ?>
            </div>
          </div>
      </div>



<div style="clear:both"></div>

</br>
<div class="b_mail">
<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'=>'subjects-form',
	
)); 
echo $this->renderPartial('_form', array(
	'model'=>$model,
	'form' =>$form
	)); ?>


<?php $this->endWidget(); ?>

</div>
</div><!-- form -->

protected/modules/schoolconfig/views/subjects/view.php
<?php

/*
 * © 2015 LOGIPAM services / www.logipam.com siges@logipam.com et contributeurs (voir www.logipam.com)
 * 
 * This file is part of SIGES.

    SIGES is a free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License.

    SIGES is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with SIGES.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

$acad_sess=acad_sess();
$acad=Yii::app()->session['currentId_academic_year'];
?>




<!-- Menu of CRUD  -->
    
<?php 
$this->breadcrumbs=array(
	Yii::t('app','Subjects')=>array('index'),
	$model->subject_name,
);  
?>

<div id="dash">
          
          <div class="span3"><h2>
<?php echo Yii::t('app',' {name}',array('{name}'=>$model->subject_name)); ?> 
</h2> </div>
     
		   <div class="span3">

        <?php 
               if(!isAchiveMode($acad_sess))
                 {       
        ?>

             <div class="span4">
                  <?php
				
                     $images = '<i class="fa fa-plus">&nbsp;'.Yii::t('app','Add').'</i>';

                               // build the link in Yii standard
                     echo CHtml::link($images,array('subjects/create')); 
                   ?>
              </div>
    
           <div class="span4">
                      <?php
				
                     $images = '<i class="fa fa-edit">&nbsp;'.Yii::t('app','Update').'</i>';

                               // build the link in Yii standard
                     echo CHtml::link($images,array('subjects/update/','id'=>$model->id,'from'=>'view')); 
                     ?>
                      
              </div>   
       <?php
                 }
      
      ?>       

              
    		<div class="span4">
                  <?php
				
                     $images = '<i class="fa fa-arrow-left"> &nbsp;'.Yii::t('app','Cancel').'</i>';

                               // build the link in Yii standard
                     echo CHtml::link($images,array('subjects/index')); 
                   ?>
            </div>      
    		 
       </div>
 </div>
 

<div style="clear:both"></div>




<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		
		'subject_name',
		'subjectParent.subject_name',
		array('name'=>'isParent','label'=>Yii::t('app','Is Subject Parent')),
                
		
	),
)); ?>



                      